### PR TITLE
typo on log message "Ignorning"

### PR DESCRIPTION
**Pull request by dcharbonnier**
Or is it on purpose ?

### CODE REVIEW

**Comment by curran** [comment]
Looks good to me! I'd vote for merge.

**Comment by curran** [comment]
@nateps @rkstedman [PR tending note] I think this PR can be merged. It would show signs of life on the project. Also there's no danger of anything breaking here.

**Comment by rkstedman** [comment]
This is an update that requires publishing the module. I'm not sure how (and if?) I can actually publish yet -- but I'll look into it

**Comment by rkstedman** [comment]
Okay! I should be able to merge and publish this... here goes!

We're at `1.0.0-beta.7` so I'll publish this fix as `1.0.0-beta.8`

**Comment by nateps** [comment]
🎉  first of many ;-)

**Comment by curran** [comment]
@nateps Woohoo excellent!

**Pull request merged**
